# blank_issues_enabled: false
# contact_links:
#   - name: General Questions
#     url: https://github.com/yourusername/dipisha-book-website/discussions
#     about: Ask general questions or engage in discussions about the project.
