name: "Deploy Frontend"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to deploy.'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: checking code structure 
        run : ls apps/frontend

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install 

      - name: Create .env file
        run: echo "NEXT_PUBLIC_API_URL=https://dipisha-website-worker-api.deepeshkalurs.workers.dev" > apps/frontend/.env

      - name: Build The Frontend
        run: pnpm --filter @dipisha/website build

      - name: Deploy to Cloudflare Production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm wrangler pages deploy out/ --project-name=dipisha
        working-directory: apps/frontend